server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: pgx
    source: postgres://pg:pg@localhost:5432/db?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

metadata:
  name: "layout"
  env: DEV
otel:
  trace:
    endpoint: "localhost:4318"
    insecure: true
  metric:
    enable_exemplar: true
log:
  filepath: "app.log"
